server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Password123*
    url: jdbc:mysql://localhost:3306/legal_tracker_db
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
